### ISSUE TITLE
Write a better README

### ISSUE THREAD

**Issue by itsharshag** [get-devkit/json-viewer#3]
The README of this chrome extension still has the content of the README of the template we used. We need to write a new README.

**Comment by Arpitgoyalgg** [comment]
Thanks for opening the issue! I have updated the [README](https://github.com/get-devkit/json-viewer/blob/main/README.md) now.

**Comment by itsharshag** [comment]
The new README looks awesome, thank you!
In the future, we can also add a photo or a gif of the extension's demo to make the README more cool :D

**Comment by Arpitgoyalgg** [comment]
Thanks for the review and the input! I have included a demo image in the docs now.
